

services:
  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 200MB
  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: 
      context : .
      dockerfile:  docker/Dockerfile.backend
    container_name: backend
    command: ["python", "backend/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    depends_on:
      - redis

  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: smtp4dev
    restart: always
    ports:
      - '5001:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev

  worker:
    build:
      context : . 
      dockerfile:  docker/Dockerfile.backend
    command: celery -A Multi_Shop worker --loglevel=info
    depends_on:
      - redis
      - backend
    volumes:
      - ./src/backend:/app

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "8900:4388"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_HOST=0.0.0.0
      - N8N_PORT=4388
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - redis
      - backend
  elasticsearch:
    image: mirror2.chabokan.net/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    mem_limit: 700MB

  kibana:
    image: mirror2.chabokan.net/elastic/kibana:8.17.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    restart: unless-stopped
    mem_limit: 350MB

  logstash:
    image: mirror2.chabokan.net/logstash:8.17.0
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "5001:5001"
      - "9600:9600"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    restart: unless-stopped
    mem_limit: 284MB
      



volumes:
  smtp4dev-data:
  esdata:
  postgres_data:
  elasticsearch_data:
  